name: Build docker build environments

on:
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:

    runs-on: ubuntu-20.04

    strategy:
        matrix:
          tag: [mips, mipsel, mtk, octeon]
          type: [kernel, tools]
          exclude:
            - tag: mips
              type: kernel
            - tag: mtk
              type: tools
            - tag: octeon
              type: tools
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/ubnt-build:${{ matrix.tag }}-${{ matrix.type }}

    steps:
      - uses: actions/checkout@v2

      - name: Build kernel environment
        if: ${{ matrix.type == 'kernel' }}
        run: docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" -f ci/DOCKERFILE-${{ matrix.tag }} .

      - name: Build tools environment
        if: ${{ matrix.type == 'tools' }}
        env:
          ARCH: ${{ matrix.tag }}
          TARGET: ${{ matrix.tag }}-linux-musl
        run: docker build --pull -t "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')" -f ci/DOCKERFILE-tools .

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: docker push "$(echo $IMAGE | tr '[:upper:]' '[:lower:]')"
